### ISSUE TITLE
 The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

### ISSUE THREAD

**Issue by celprov** [nipreps/nipreps.github.io#22]
My latest PR fails because the build image is no longer supported.
https://app.netlify.com/sites/vigorous-brahmagupta-fd6bf1/deploys/63ea4891d59e4200087702c1

The build image can upgraded to the latest build image in the Netlify UI under Site settings > Build & deploy > Continuous Deployment > Build image selection as described in https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239.

cc/ @esavary

**Comment by oesteban** [comment]
I have disconnected netlify. Let's build the previews through RTD
