### ISSUE TITLE
Support permanent links (especially, for each of the news entries)

### ISSUE THREAD

**Issue by oesteban** [nipreps/nipreps.github.io#26]
### What would you like to see added in this software?

See how to enable permalinks here - https://www.mkdocs.org/user-guide/writing-your-docs/

Then, make sure we have this set up for the news section.

### Do you have any interest in helping implement the feature?

Yes

**Comment by effigies** [comment]
Permalinks have been enabled since a4e18424c960cf2290c7b049cee31afb84ab1678.
